### ISSUE TITLE
Show correspondence between objects in text and visual

### ISSUE THREAD

**Issue by josephsweeney** [YouClid/youclid#18]

**Comment by DrewMonroe** [comment]
Base functionality merged in 8b073ffa8c7ed1dc5e20f2e106aca0599951272e

**Comment by DrewMonroe** [comment]
Centers still need to reworked in the backend to actually have an id of `text_point_name`, and  we need to figure out how to deal with triangles (and other polygons)

**Comment by josephsweeney** [comment]
You can now highlight either the text or the visual to see correspondence.

The next step is to actually assign decent color to the objects so that you can see the correspondence without mousing over each element.

**Comment by josephsweeney** [comment]
Things to do:

- [ ] Backend adds colors to geometry data

- [ ] Frontend colors the text and the geometry

- [ ] Frontend adds highlighting that shows individual correspondence
