### ISSUE TITLE
Do not output styles in the html

### ISSUE THREAD

**Issue by josephsweeney** [YouClid/youclid#71]
The output html has `<span name=text_line_AB style='background-color: #dddddd'>line AB</span>`

Instead we need to give it a css class so these spans can be styled with CSS, specifying the background explicitly for every `span` prevents that.

**Comment by josephsweeney** [comment]
When adding the CSS class, it would be useful to include an id as well, so that each geometric object can be colored individually.

**Comment by DrewMonroe** [comment]
Agreed, good call. Should be trivial to do
