### ISSUE TITLE
Having [step] and [clear] on their own lines adds whitespace to the text

### ISSUE THREAD

**Issue by DrewMonroe** [YouClid/youclid#91]
If I have the following:
```
This is a [line AB]
[step]
[clear]
```
If will produce the following text
```
This is a [line AB]
\n
\n
```
We probably just want nothing to be displayed, instead of a new line

**Comment by saileshsimhadri** [comment]
I'm not sure if this is what we want. Since the user explicitly put in newlines, should we not add in newlines as well?

**Comment by DrewMonroe** [comment]
Hmm, it's a fair point. I suppose my reasoning for doing it was because I wanted it to be more readable what I was doing. I feel like
```
This is some text [line AB] and here is more text [point C].
And this is more stuff, I'm just taking up space [step]
And now this is the next step [line BC]
```
Is harder to find where the `[step]` is, as opposed to putting it on its own line. With that said, I see your point, maybe you actually want a blank line there. You could make the argument that if you want a blank line, you have to actually put a blank line in there. Thoughts?

**Comment by saileshsimhadri** [comment]
That was exactly my point. If they wanted no new lines, there is a way to do it. I don't think readability is more important than this.

**Comment by DrewMonroe** [comment]
Okay, I'm okay with whatever, so you can close the issue if you don't think we should change anything
